In [6]:
import numpy as np
#CLASS TASK-I
#Find the size in bytes of each element of the array.
#eg an array of elements of type float64 has itemsize 8 (=64/8).import numpy as np
x=np.array([1,2,3])
x.itemsize
y=np.array([1.2,2.3,4.5])
x.itemsize

4

In [43]:
#CLASS TASK-II
#create a 3*3 n-dim array
#1st row create 3 numbers from np.empty,
#2nd row create 3 nos from np.zeros
#3rd row create 3 nos from np.ones
x=np.array([np.empty(shape=(1,3),dtype=int),np.zeros(shape=(1,3),dtype=int),np.ones(shape=(1,3),dtype=int)])
print(x)


[[[1 1 1]]

 [[0 0 0]]

 [[1 1 1]]]


In [60]:
#CLASS TASK-III
#create an array of 10 nos and slice it
#to print 5th,7th,9th elet from thestrat
#do the same using negative indexing
x=np.linspace(11,45,10,dtype=int)
print(x)
print("Enter the 5th,7th and 9th elt: ",x[4],x[6],x[8])
print("now using negative indexing ",x[-2],x[-4],x[-6])


[11 14 18 22 26 29 33 37 41 45]
Enter the 5th,7th and 9th elt:  26 33 41
now using negative indexing  41 33 26


In [2]:
#CLASS TASK-IV
#create a 1d array with random nos
#print another array only whoch returns int
x=np.array([1,2.3,5.6,33,34.56,4,4.55,5.66])
y=x.astype(int)

NameError: name 'np' is not defined

In [3]:
#CLASS TASK-V
#consider X
x=np.array([[0,1,2],[3,4,5],[6,7,8]])
#construct the following 2d array from the contents of x
p=np.array([[x[0,0],x[0,1]],[x[2,2],x[2,2]]])

NameError: name 'np' is not defined

In [4]:
#CLASS TASK-VI
#difference between resize and reshape in numpy array
r=np.arange(16)
np.shape(r)
r.reshape(4,4) #returns a reshaped array but the original remains unchanged
r.resize(4,4) #change is made in original array

NameError: name 'np' is not defined

In [3]:
#CLASS TASK-VII
#difference btw ravel and flatten




In [4]:
#CLASS TASK-VIII
#consider an array
x=np.array([[42,22,12],[44,53,66]])
#perform reshape, flatten, transpose, hstack and vstack
x.reshape(3,2)
x.flatten()
print(x.T)
y=np.ones((2,2))
z=np.zeros((4,3))
hh=np.hstack((x,y))
vv=np.vstack((x,z))
print('The value is: ',x)
print('the size of the array x is: ',np.shape(x))
print('the hstack is',hh)
print('the vstack is:',vv)

NameError: name 'np' is not defined

In [7]:
#CLASS TASK-IX
#consider an array 
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])

#1
a=a.flatten()
print('the array a is: ',a)
y=np.where(a<5)
print('np.where(a<=5) is: ',y)

#2
print('np.cumsum(x): ',np.cumsum(x))

#3
print('np.unique(x): ',np.unique(x))

#4
print('np.sort(x): ',np.sort(x))

#5
print('np.sum is: ',np.sum(x))
print('np.min is: ',np.min(x))
print('np.max is: ',np.max(x))
print('np.argmax is: ',np.argmax(x))
print('np.argmin is: ',np.argmin(x))

the array a is:  [ 1  2  4  7  9 88  6 45  9 76  3  4]
np.where(a<=5) is:  (array([ 0,  1,  2, 10, 11], dtype=int64),)
np.cumsum(x):  [1 3 6]
np.unique(x):  [1 2 3]
np.sort(x):  [1 2 3]
np.sum is:  6
np.min is:  1
np.max is:  3
np.argmax is:  2
np.argmin is:  0


In [8]:
#CLASS TASK-X
#1. gen random nos from normal dist with size10
#2. gen random nos from binomial dist
#import scipy.stats
x=np.random.normal(size=10)
print('Numbers from a normal dist: ',x)
y=np.random.binomial(15,0.2,12)
print('\nNumbers from a binomial distribution: ',y)

Numbers from a normal dist:  [ 0.22126888 -0.79441917 -2.48510637 -0.22214784 -1.0133908  -1.14171546
 -0.34569824 -1.51240707 -0.35713885 -0.35492418]

Numbers from a binomial distribution:  [2 2 2 1 6 3 2 3 3 3 4 1]


In [9]:
#CLASS TASK-XI
#1.np.savetxt
x=np.savetxt('SavingMyFirstTextFile.txt',x,delimiter=',')
#2.np.loadtxt
from io import StringIO
c=StringIO("0 1 2 \n3 4 5")
d=np.loadtxt(c)
#3.np.tofile
np.array([1,2,3]).tofile("a.bin")
print(np.fromfile("a.bin",dtype=np.int64))
#4.np.fromfile
np.fromfile('SavingMyFirstTextFile.txt',dtype=float,count=-1,sep='')
#5.np.savez
np.savez('SavingMyFirstTextFile.txt')


[8589934593]


In [10]:
#CLASS TASK-XII
#perform the set operations on the following array:
x=[[3,5,2,4],[7,6,8,8],[1,6,7,7]]
#intersection
print('\nnp.intersection1d(x[0],x[1],x[2]): ',np.intersect1d((x[0],x[1]),x[2]))
#union
print('\nnp.union1d(x[0],x[1],x[2]): ',np.union1d((x[0],x[1]),(x[2])))
#setDifference
print('\nnp.setdiff1d(x[0],x[1]): ',np.setdiff1d(x[0],x[1]))
#set XOR
print('\nnp.setxor1d(x[0],x[1]): ',np.setxor1d(x[0],x[1]))


np.intersection1d(x[0],x[1],x[2]):  [6 7]

np.union1d(x[0],x[1],x[2]):  [1 2 3 4 5 6 7 8]

np.setdiff1d(x[0],x[1]):  [2 3 4 5]

np.setxor1d(x[0],x[1]):  [2 3 4 5 6 7 8]


In [11]:
#CLASS TASK-XIII
#implement other methods mentioned in the image(abs,exp,sin,cos...) on arr
from numpy.random import randn
arr=np.array(randn(4,4)*10,dtype=np.int8)
print(arr)
print('The sqrt method: ',np.sqrt(arr))
print('The absolute method: ',np.abs(arr))
print('The exp is: ',np.exp(arr))
print('The sign method: ',np.sign(arr))
print('The sin, cos, tan are: ',np.sin(arr),np.cos(arr),np.tan(arr))
print('the isnan identifier is: ',np.isnan(arr))
print('Is infinity or not: ',np.isinf(arr),np.isfinite(arr))

[[  8   3  -2   7]
 [  6   2   2   3]
 [  3   0   0  12]
 [  7 -13   6   6]]
The sqrt method:  [[2.828 1.732   nan 2.646]
 [2.45  1.414 1.414 1.732]
 [1.732 0.    0.    3.465]
 [2.646   nan 2.45  2.45 ]]
The absolute method:  [[ 8  3  2  7]
 [ 6  2  2  3]
 [ 3  0  0 12]
 [ 7 13  6  6]]
The exp is:  [[2.980e+03 2.008e+01 1.354e-01 1.097e+03]
 [4.035e+02 7.391e+00 7.391e+00 2.008e+01]
 [2.008e+01 1.000e+00 1.000e+00       inf]
 [1.097e+03 2.265e-06 4.035e+02 4.035e+02]]
The sign method:  [[ 1  1 -1  1]
 [ 1  1  1  1]
 [ 1  0  0  1]
 [ 1 -1  1  1]]
The sin, cos, tan are:  [[ 0.9893  0.1411 -0.909   0.657 ]
 [-0.2793  0.909   0.909   0.1411]
 [ 0.1411  0.      0.     -0.5366]
 [ 0.657  -0.4202 -0.2793 -0.2793]] [[-0.1455 -0.99   -0.4163  0.754 ]
 [ 0.96   -0.4163 -0.4163 -0.99  ]
 [-0.99    1.      1.      0.8438]
 [ 0.754   0.907   0.96    0.96  ]] [[-6.8    -0.1426  2.186   0.8716]
 [-0.291  -2.186  -2.186  -0.1426]
 [-0.1426  0.      0.     -0.6357]
 [ 0.8716 -0.4631 -0.291  -0.291 ]]
t

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in sqrt
  
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  
